<?php $escape = $this->plugin('escapeHtml');?>
<?php $this->htmlElement('body')->appendAttribute('class', 'item resource browse');
$query = $this->params()->fromQuery(); ?>
<?php if (isset($itemSet)): ?>
<?php $this->htmlElement('body')->appendAttribute('class', 'item-set');
    $query['item_set_id'] = $itemSet->id(); ?>
<?php endif; ?>
<div class="clearfix">&nbsp;</div>
<?php if (isset($itemSet)): ?>
    <?php echo $this->pageTitle($itemSet->displayTitle(), 2); ?>
    <h3><?php echo $this->translate('Item Set'); ?></h3>
    <div class="metadata">
        <?php echo $itemSet->displayValues(); ?>
    </div>
    <?php echo $this->pageTitle($this->translate('Items'), 3); ?>
<?php else: ?>
    <?php echo $this->pageTitle($this->translate('Items'), 2); ?>
<?php endif; ?>

<?php echo $this->searchFilters(); ?>
<?php echo $this->pagination(); ?>
<div class="row resource-list">
    <?php foreach ($items as $item): ?>
    <div class="col-md-4 item resource">
        <?php if ($primaryMedia = $item->primaryMedia()): ?>
        <?php echo $item->linkRaw($this->thumbnail($primaryMedia, 'large')); ?>
        <?php endif; ?>
        <div class="title"><?php echo $item->link($item->displayTitle()); ?></div>
        
    </div>
    <?php endforeach; ?>
</div>
